baseURL = 'johnxrd.github.io/'
languageCode = 'en-us'
title = 'johnxrd'
theme = 'etch'
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "I need a book to heal my mind."
  copyright = "Copyright Â© 2023 Cebotari Ion."
  dark = "on"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true