baseURL = 'iamjohncb.github.io/'
languageCode = 'en-us'
title = 'John CB ðŸ’»'
theme = 'etch'
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "I need a book to heal my mind."
  copyright = "Copyright Â© 2023 Cebotari Ion."
  dark = "on"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "ðŸ“Œposts   "
    name = "ðŸ“Œposts   "
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "   ðŸ“Œabout   "
    name = "   ðŸ“Œabout   "
    title = "about"
    url = "/about/"
    weight = 20
  
  [[menu.main]]
    identifier = "   ðŸ“Œschedule TI-237"
    name = "   ðŸ“Œschedule TI-237"
    title = "schedule"
    url = "/schedule/"
    weight = 20

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
